#!/bin/python
#
# LC
#

from datetime import datetime
import os
import StringIO
from optparse import OptionParser, OptionGroup

try:
	import FingerPrint, FingerPrint.sergeant
except ImportError:
	#we need this when we run unittest
        import sys
        sys.path.append("./")
	import FingerPrint, FingerPrint.sergeant

from FingerPrint.swirl import Swirl
from FingerPrint.blotter import Blotter
from FingerPrint.serializer import PickleSerializer


def main():
    #
    # set up the option parser
    # 
    usage = "usage: %prog [-c|-y|-d] [options] inputfile1 ... inputfileN"
    parser = OptionParser(usage, version=FingerPrint.version)
    #what are we going to do
    group = OptionGroup(parser, "Required Options",
                    "You must select one of these options")
    parser.add_option_group(group)

    group.add_option("-c", "--create", action="store_true", dest="create",
                    default=False,
                    help="Create a swirl from the given input file names")
    group.add_option("-y", "--verify", action="store_true", dest="verify",
                    default=False,
                    help="Scan the current system to verify compatibility with given swirl")
    group.add_option("-d", "--display", action="store_true", dest="display",
                    default=False,
                    help="Display the content of the given swirl file")
    #various option
    parser.add_option("-f", "--file", dest="filename", default='output.swirl',
                    help="write or read swirl FILE", metavar="FILE")
    parser.add_option("-n", "--name", dest="name", default="Swirl",
                    help="the name of the swirl, default to Swirl")
    parser.add_option("-l", "--filelist", dest="filelist", default=None,
                    help="a file containing a list of file which will be " + \
                    "included to this swirl")
    parser.add_option("-v", "--verbose", action="store_true", dest="verbose", 
                    default=False,
                    help="Output a textual representation of the swirl")
    (options, args) = parser.parse_args()
   
 
    #
    # switch based on user input
    #
    if (options.verify + options.create + options.display) != 1:
        #too many flags
        parser.error("Only one of the flag -y -c -d can be used at a time" )

    if options.verify :
        #verify the current swirl
        serg = FingerPrint.sergeant.readFromPickle(options.filename)
        if not serg.check():
            #error let print some stuff
            print "On the current system the swirl %s can not be " % options.filename + \
                "completely verified.\n" 
            print "Dependency ", serg.getError(), " can not be found"
            return -1
        else:
            print "Swirl %s pass the test" % options.filename
            return 0

    elif options.create :
        #create a swirl 
        filenameList = []
        if options.filelist :
            #read the input filelist from file
            try:
                filelistfd = open(options.filelist)
                for i in filelistfd:
                    filenameList.append(i.strip())
            except IOError as e:
                parser.print_help()
                parser.error("The file %s does not exist on this system." % options.filelist)
        if filenameList == []:
            #get the filelist from command line
            filenameList = args
        if len(filenameList) < 1:
            parser.print_help()
            parser.error("you need to specify at least one inputfile or the FILELIST parameter")
        for fileName in filenameList:
            #TODO move this in blotter
            if not os.path.exists(fileName):
                parser.print_help()
                parser.error("The file %s does not exist on this system." % fileName)
        #creating blotter
        blotter = Blotter(options.name, filenameList)
        if options.verbose:
            print "swirl structure:\n", blotter.getSwirl()
            #self.assertEqual(self.seq, range(10))
            print "list of global dependecies:\n", blotter.getSwirl().getDependencies()
            print "list of global provides:\n", blotter.getSwirl().getProvides()
        if options.filename:
            #this should be always true
            outputfd = open(options.filename, 'w')
            pickle = PickleSerializer( outputfd )
            pickle.save(blotter.getSwirl() )
            outputfd.close()
            print "file %s saved" % options.filename
        #success
        return 0
    elif options.display :
        #display the swirl
        if options.filename :
            serg = FingerPrint.sergeant.readFromPickle(options.filename)
            print "File name: ", options.filename
            print "Swirl Structure:\n", serg.getSwirl()
            print "Global Dependencies:  " , serg.getSwirl().getDependencies()
            print "Global Provide:  ", serg.getSwirl().getProvides()
        return 0
    else:
        parser.print_help()
        parser.error( "You must select at least one option between -d -c -y" )
    

if __name__ == "__main__":
    main()

