#!/bin/python
#
# LC
#

from datetime import datetime
import os
import StringIO
from optparse import OptionParser

import FingerPrint, FingerPrint.sergeant
from FingerPrint.swirl import Swirl
from FingerPrint.blotter import Blotter
from FingerPrint.serializer import PickleSerializer


def main():
    usage = "usage: %prog [options] inputfile1 ... inputfileN"
    parser = OptionParser(usage, version=FingerPrint.version)
    parser.add_option("-f", "--file", dest="filename", default='output.swirl',
                    help="write or read swirl FILE", metavar="FILE")
    parser.add_option("-n", "--name", dest="name", default="Swirl",
                    help="the name of the swirl, default to Swirl")
    parser.add_option("-l", "--filelist", dest="filelist", default=None,
                    help="a file containing a list of file which will be " + \
                    "included to this swirl")
    parser.add_option("-v", "--verbose", action="store_true", dest="verbose", 
                    default=False,
                    help="Output a textual representation of the swirl")
    parser.add_option("-s", "--scan", action="store_true", dest="scan",
                    help="Scan the current system for compatibility with given swirl")


    
    (options, args) = parser.parse_args()

    if options.scan :
        #we have to scan let's read the swirl
        serg = FingerPrint.sergeant.readFromPickle(options.filename)
        if not serg.check():
            #error let print some stuff
            print "On the current system the swirl %s can not be completely " +\
                    "verified.\n\n" % options.filename
            print "Error:\n", serg.getError()
            return -1
        else:
            print "Swirl %s pass the test" % options.filename
            return 0



    #check if we read the list of file from a file
    filenameList = []
    if options.filelist :
        #read the input filelist from file
        try:
            filelistfd = open(options.filelist)
            for i in filelistfd:
                filenameList.append(i.strip())
        except IOError as e:
            parser.print_help()
            parser.error("The file %s does not exist on this system." % options.filelist)
    if filenameList == []:
        #get the filelist from command line
        filenameList = args
    if len(filenameList) < 1:
        parser.print_help()
        parser.error("you need to specify at least one inputfile or the FILELIST parameter")
    for fileName in filenameList:
        #TODO move this in blotter
        if not os.path.exists(fileName):
            parser.print_help()
            parser.error("The file %s does not exist on this system." % fileName)
    #creating blotter
    blotter = Blotter(options.name, filenameList)
    if options.verbose:
        print "swirl structure:\n", blotter.getSwirl()
        #self.assertEqual(self.seq, range(10))
        print "list of global dependecies:\n", blotter.getSwirl().getDependencies()
        print "list of global provides:\n", blotter.getSwirl().getProvides()
    if options.filename:
        outputfd = open(options.filename, 'w')
        pickle = PickleSerializer( outputfd )
        pickle.save(blotter.getSwirl() )
        outputfd.close()
        print "file %s saved" % options.filename
    return 0
    

if __name__ == "__main__":
    main()

